services:
  # WordPress
  wordpress:
    image: wordpress:php8.3-fpm-alpine
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
    volumes:
      - ./web/php-fpm.conf:/usr/local/etc/php-fpm.d/custom.conf
      - php_logs:/var/log/php-fpm
    networks:
      - monitoring
    depends_on:
      - mysql

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/wordpress:/var/www/html
      - nginx_logs:/var/log/nginx
    depends_on:
      - wordpress
    networks:
      - monitoring

  # Mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    networks:
      - monitoring
    volumes:
      - mysql:/var/lib/mysql
      - mysql_logs:/var/log/mysql

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafanadb:/var/lib/grafana
    networks:
      - monitoring

  # Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.16.2
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - beats_logs:/var/log/beats
    user: "0:0"
    ports:
      - "5044:5044"
    networks:
      - monitoring

  # Loki
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    user: "0:0"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - lokidb:/tmp/loki
    networks:
      - monitoring

  # Promtail
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yml
      - beats_logs:/var/log/beats
    networks:
      - monitoring
    depends_on:
      - loki

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.16.2
    container_name: filebeat
    volumes:
      - ./beats/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - nginx_logs:/var/log/nginx
      - mysql_logs:/var/log/mysql
      - php_logs:/var/log/php-fpm
    networks:
      - monitoring
    depends_on:
      - logstash

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.16.2
    container_name: metricbeat
    volumes:
      - ./beats/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    networks:
      - monitoring
    depends_on:
      - logstash

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:8.16.2
    container_name: heartbeat
    volumes:
      - ./beats/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    networks:
      - monitoring
    depends_on:
      - logstash

networks:
  monitoring:

volumes:
  mysql:
    driver: local
  grafanadb:
    driver: local
  lokidb:
    driver: local
  mysql_logs:
    driver: local
  nginx_logs:
    driver: local
  php_logs:
    driver: local
  beats_logs:
    driver: local
