services:
  # WordPress
  wordpress:
    image: wordpress:php8.3-fpm-alpine
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
    volumes:
      - ./web/php-fpm.conf:/usr/local/etc/php-fpm.d/custom.conf
      - php_logs:/var/log/php-fpm
    networks:
      - monitoring
    depends_on:
      - mysql

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/wordpress:/var/www/html
      - nginx_logs:/var/log/nginx
    depends_on:
      - wordpress
    networks:
      - monitoring

  # Mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    networks:
      - monitoring
    volumes:
      - mysql:/var/lib/mysql
      - mysql_logs:/var/log/mysql

  opensearch:
    image: opensearchproject/opensearch:2.18.0
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Slozhniparol123
    volumes:
      - ./opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - opensearchdb:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    networks:
      - monitoring

  dataprepper:
    image: opensearchproject/data-prepper:2.10.2
    container_name: dataprepper
    volumes:
      - ./dataprepper/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./dataprepper/data-prepper-config.yaml:/usr/share/dataprepper/data-prepper-config.yaml
    ports:
      - "2021:2021"
    networks:
      - monitoring
    depends_on:
      - opensearch

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    networks:
      - monitoring

  fluentbit:
    image: fluent/fluent-bit:3.2.4-amd64
    container_name: fluentbit
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - nginx_logs:/var/log/nginx
      - mysql_logs:/var/log/mysql
      - php_logs:/var/log/php-fpm
    networks:
      - monitoring
    depends_on:
      - dataprepper

networks:
  monitoring:

volumes:
  mysql:
    driver: local
  mysql_logs:
    driver: local
  nginx_logs:
    driver: local
  php_logs:
    driver: local
  opensearchdb:
    driver: local
