metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - memory
      - network
    period: 10s
  - module: nginx
    metricsets: ["stubstatus"]
    period: 10s
    hosts: ["http://nginx"]
    server_status_path: "status"

output.logstash:
  hosts: ["logstash:5044"]
