metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - memory
      - network
    period: 10s
  - module: nginx
    metricsets: ["stubstatus"]
    period: 10s
    hosts: ["http://localhost"]

output.elasticsearch:
  hosts: ["http://localhost:9200"]
setup.kibana:
  host: "http://localhost:5601"
