server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: beats
    static_configs:
      - targets:
          - localhost
        labels:
          job: beats
          __path__: /var/log/beats/beats.log
    pipeline_stages:
      - json:
          expressions:
            log_level: log.level
            message: message
            service_name: service.type
            source: metricset.name
            exporter: agent.type
            monitor_status: monitor.status
      - labels:
          log_level: log_level
          service_name: service_name
          source: source
          exporter: exporter
          status: monitor_status
      - timestamp:
          source: timestamp
          format: RFC3339
